baseURL: "https://cgutierr-zgz.github.io/"
title: cgutierr-zgz
paginate: 5
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: cgutierr-zgz
  description: "My personal website"
  keywords: [Website, Portfolio]
  author: cgutierr-zgz
  DateFormat: "2 January, 2006"
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  label:
    text: "cgutierr-zgz"
    icon: /apple-touch-icon.png
    iconHeight: 35
  profileMode:
    enabled: true
    title: "Hi there \U0001F44B"
    subtitle: "Welcome to my website"
    buttons:
      - name: github
        url: "https://github.com/cgutierr-zgz"
      - name: linkedin
        url: "https://www.linkedin.com/in/cgutierr"
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: |
      Contact me at carlosgutimo.3d@gmail.com
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  editPost:
    URL: "https://github.com/cgutierr-zgz/cgutierr-zgz.github.io/blob/master/content"
    Text: "Suggest Changes"
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
languages:
  en:
    languageName: "English"
    weight: 1
